name: Build and Deploy Airflow

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: richardfelix/finportal-airflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ github.ref_name }} .
        docker tag $IMAGE_NAME:${{ github.ref_name }} $IMAGE_NAME:latest

    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME:${{ github.ref_name }}
        docker push $IMAGE_NAME:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: finportal-airflow
        images: $IMAGE_NAME:${{ github.ref_name }}
